### ISSUE TITLE
Prosim o kontrolu ukolu 01 a 02

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#1]

**Comment by lutydlitatova** [comment]
### 1
Super řešení 👍

### 2
Super řešení 👍
Tip: Hodnoty počtu kusů zboží na skladu jsou už typu `int`, takže ani není nutné dělat převod `int(sklad[kod])` [tady](https://github.com/miskazava/python-012021/blob/9293f1aba38c3108a2c99c519a2a84b347ce37fc/priklad02.py#L11) a [tady](https://github.com/miskazava/python-012021/blob/9293f1aba38c3108a2c99c519a2a84b347ce37fc/priklad02.py#L17), klidně můžeš použít přímo `sklad[kod]`.
