### ISSUE TITLE
Prosim o kontrolu prikladov 31-34

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#10]
Dakujem!

**Comment by lutydlitatova** [comment]
#### 31
👍 

#### 32
👍  Vytváříš histogram i čísla zaměstnance, který nemá žádný význam, takže by stačilo něco jako
```python
# ...
platy["plat"].hist()  # Vybereme sloupec o platech
plt.show()
```

#### 33,34
👍 


Skvělé, píšu 4 body za 7. sadu!
