### ISSUE TITLE
Prosim o kontrolu priklad03, priklad04, priklad05

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#2]

**Comment by miskazava** [comment]
[priklad03](https://github.com/miskazava/python-012021/blob/8b2d56cf42ac9e5108ce0a693d472596366488b5/priklady/priklad03.py)
[priklad04](https://github.com/miskazava/python-012021/blob/8b2d56cf42ac9e5108ce0a693d472596366488b5/priklady/priklad04.py)
[priklad05](https://github.com/miskazava/python-012021/blob/8b2d56cf42ac9e5108ce0a693d472596366488b5/priklady/priklad05.py)

**Comment by lutydlitatova** [comment]
#### 3
Vypadá to na dobré cestě! Jen připomínám, že program má vypsat "počet volných místností, které jsou k dispozici" (ne které).

#### 4
Super řešení 👍

#### 5
Pěkný 👍 , zkus ještě řešení zjednodušit, třeba takhle
```
prodejCelkem = 0

if kniha in prodeje2019:
    ... <dopln>
if kniha in prodeje2020:
    ... <dopln>

print(f"Celkem se prodalo {prodejCelkem} ks.")
```

**Comment by miskazava** [comment]
Ďakujem za tipy :) Príklady 03 a 05 som opravila. Prosím o finálnu kontrolu. Vďaka!

**Comment by lutydlitatova** [comment]
Skvěle  👍 Máš vše v pořádku, zavírám issue 🙂
