### ISSUE TITLE
Prosim o kontrolu prikladov 09 a 10.

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#4]
9. mi prisiel dost zlozity. Mozno by to riesenie slo nejako inak?
Dakujem!

**Comment by lutydlitatova** [comment]
#### 9
Super řešení 👍  Napadá mne například tohle "vylepšení", ale jak to máš je to také správně:
- hned na začátku zkontrolovat, jestli student má pětku nebo trojku:
  ```python
  def ohodnot_studenta(znamky):
      if 5 in znamky.values():
          # neprospel
      if 3 in znamky.values():
          # ma trojku
  ```

#### 10
Moc pěkné řešení 👍
