### ISSUE TITLE
Prosim o kontrolu prikladov 11 - 15

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#5]
Dakujem!

**Comment by lutydlitatova** [comment]
#### 11
Super řešení 👍  Ani není potřeba funkce  `Auto.obsazenost()`, ale ničemu ani nevadí 🙂 

#### 12
Super řešení 👍 Ve funkci `pujc_auto` můžeš mírně zjednodušit podmínku `if self.volne == False:...` na `if not self.volne: ...`, ale to je spíš kosmetická věc.

#### 13
Super řešení 👍 Při vracení auta bychom mohli přepsat přímo `self.pocetKilometru`, ale nový atribut `self.tachometr` je také OK

#### 14
Skvěle 👍

#### 15
Skvěle 👍

Píšu 5 bodů!
