### ISSUE TITLE
Prosim o kontrolu prikladov 16 a 17

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#6]
Dakujem

**Comment by lutydlitatova** [comment]
#### 16, 17
Super 🙂 Jen pár drobností:

- Není nutné převádět proměnné `delka`, `pocetEpizod`, `delkaEpizody` na `int`, protože parametr už (správně) zadáváš jako číslo (viz např. [řádka 30](https://github.com/miskazava/python-012021/blob/78e4c32db91e50b27be8507bc2e3f918cdbaf56a/priklady/priklad16.py#L30))

- Ve funkcích `get_info` u tříd, které dědí z `Polozka` (tj. `Film` a `Serial`) můžeš využít volání funkce `get_info` právě od `Polozka`, ušetříme si vypisování `self.nazev` a `self.zanr`:

Např.
```python
class Polozka:
    def get_info(self):
        return f"název filmu: {self.nazev}, žánr: {self.zanr}")
        
class Film(Polozka):
    def get_info(self):
        # super().get_info() znamena "zavolej funkci get_info() od meho rodice" - v tomto pripade `Polozka`
        return super().get_info() + "delka: {self.delka}"
```

Dobře vybraný film a seriál 😁

**Comment by miskazava** [comment]
Ahoj,

jasneee, toto mi prave bolo divne ze to musim vzdy opakovat ale nevedela som prist na to ako to urobit cez to super(), a pritom tak jednoduche 😊 Dakujem, opravila som!

Som rada, ze niekto zdiela moje sympatie k feministickej kinematografii 😁

**Comment by lutydlitatova** [comment]
Ještě poslední komentář - Koukala jsem, že jsi přidala i tu zakomentovanou řádku, to byl fakt jen komentář, myslela jsem to takhle, omlouvám se za zmatení:

```python
class Polozka:
    def get_info(self):
        return f"název filmu: {self.nazev}, žánr: {self.zanr}")
        
class Film(Polozka):
    def get_info(self):
        return super().get_info() + "delka: {self.delka}"
```

Nemusíš opravovat, jen pro tebe, aby to bylo jasnější...
