### ISSUE TITLE
Prosim o kontrolu prikladov 18,19,20

### ISSUE THREAD

**Issue by miskazava** [miskazava/python-012021#7]
Vdaka :)

**Comment by lutydlitatova** [comment]
Zatím nikde nevidím, nezapomněla jsi je nahrát? 🙂

**Comment by miskazava** [comment]
Ja mam problem, ze somo pushla ale v gihube to neviem najst. Zaroven to nemozem nahrat znovu lebo pycharm sa tvari ze vsetko uz pushnute bolo.

**Comment by lutydlitatova** [comment]
Uz je vidim, hned se na to podivam 🙂

**Comment by lutydlitatova** [comment]
#### 18
- třídě `Uchazec` chybí v konstruktoru parametry `jmeno` a `email`:
```python
class Uchazec(Kontakt):
    def __init__(self. jmeno, email, datum_pohovoru):
        super().__init__(jmeno, email)
        ...
````
- proměnná `aktualni_datum` není definovaná.
- `datum_pohovoru` na [řádce 13](https://github.com/miskazava/python-012021/blob/948cdd548bd5674bfa9b701be1f94a87ad9316dc/priklady/priklad18.py#L13) by měl být atribut (takže  `self.datum_pohovoru`)
- pro porovnání aktuálního data s nějakým jiným můžeš využít modul `datetime`, viz kapitola [Datum a čas](https://kodim.cz/czechitas/progr2-python/python-pro-data-1/datum)

#### 19
Super! 👍 

#### 20
Super! 👍 

Celkově zatím píšu za čtvrtou sadu 4 body z 5.

**Comment by miskazava** [comment]
Dakujem a opravila som c.18. Pardon mam trosku meskanie s ukolmi :( ale uz som nahrala aj 21-25

**Comment by lutydlitatova** [comment]
#### 18

Pěkně, díky 🙂
